version: '3.9'

services:
  backend:
    image: movie-manager:0.0.1-SNAPSHOT
    restart: always
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?currentSchema=movie_directory
      - SPRING_DATASOURCE_USERNAME=movieuser
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  postgres:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=movieuser
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - ./db/data:/var/lib/postgresql/data
