spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: movieuser
    password: postgres123
  flyway:
    schemas: movie_directory
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect