spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=movie_directory
    username: movieuser
    password: postgres123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

tmdb:
  baseUrl: https://api.themoviedb.org
  apiKey: 22658692d7dc32845ab997b8db5b87f7
